language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - python setup.py install
  - pip install -r requirements-dev.txt
  - pip install python-coveralls

# command to run tests
script:
  # Ignoring test_iis.py as it requires a windows host, this is run in appveyor instead
  - py.test --cov ntlm3 --cov-report term-missing test --ignore test/integration/test_iis.py

after_success:
  - coveralls

